import Foundation

/// Generates a 3D LUT (Cube format) to convert log-encoded RGB to Rec.709 display space.
///
/// Workflow:
///   - Footage shot with sLog3Approx → use the sLog3Approx inverse LUT
///
/// Standard .cube format (Adobe/Resolve compatible):
///   - Header with LUT_3D_SIZE
///   - One line per RGB triplet, space-separated floats
///   - Values in [0.0, 1.0] range
enum LUTGenerator {
    /// Generate a .cube format LUT string for the given log curve.
    ///
    /// - Parameters:
    ///   - curve: The log curve to generate the inverse LUT for.
    ///   - size: LUT dimensions (e.g., 33 → 33×33×33 = 35,937 entries).
    ///           33 is the standard for most grading apps. 17 is faster but lower quality.
    /// - Returns: A complete .cube file as a String.
    static func generate(for curve: LogCurveType, size: Int = 33) -> String {
        var lines: [String] = []

        // Header
        lines.append("# RawLogCam Inverse LUT — \(curve.displayName) → Rec.709")
        lines.append("# Generated by RawLogCam")
        lines.append("# Apply this LUT to log-encoded footage to restore normal contrast.")
        lines.append("#")
        lines.append("TITLE \"RawLogCam \(curve.displayName) to Rec.709\"")
        lines.append("LUT_3D_SIZE \(size)")
        lines.append("DOMAIN_MIN 0.0 0.0 0.0")
        lines.append("DOMAIN_MAX 1.0 1.0 1.0")
        lines.append("")

        // Generate LUT entries
        // .cube format: iterate B (outer) → G (middle) → R (inner)
        let step = 1.0 / Float(size - 1)

        for b in 0..<size {
            for g in 0..<size {
                for r in 0..<size {
                    let encodedR = Float(r) * step
                    let encodedG = Float(g) * step
                    let encodedB = Float(b) * step

                    let encoded = SIMD3<Float>(encodedR, encodedG, encodedB)
                    let linear = LogCurve.inverse(encoded, type: curve)

                    // Apply a simple Rec.709 gamma curve (linear → display)
                    let display = applyRec709Gamma(linear)

                    // Clamp to [0, 1]
                    let clamped = SIMD3<Float>(
                        max(0, min(1, display.x)),
                        max(0, min(1, display.y)),
                        max(0, min(1, display.z))
                    )

                    lines.append(String(format: "%.6f %.6f %.6f", clamped.x, clamped.y, clamped.z))
                }
            }
        }

        return lines.joined(separator: "\n")
    }

    /// Rec.709 OETF (linear → display gamma).
    /// Standard transfer function for SDR displays.
    private static func applyRec709Gamma(_ linear: SIMD3<Float>) -> SIMD3<Float> {
        return SIMD3<Float>(
            rec709GammaSingle(linear.x),
            rec709GammaSingle(linear.y),
            rec709GammaSingle(linear.z)
        )
    }

    private static func rec709GammaSingle(_ linear: Float) -> Float {
        if linear < 0.018 {
            return 4.5 * linear
        } else {
            return 1.099 * pow(linear, 0.45) - 0.099
        }
    }

    /// Generate a 1D LUT (for preview/waveform monitoring, not for grading).
    /// Useful for verifying the curve shape.
    static func generate1D(for curve: LogCurveType, size: Int = 1024) -> String {
        var lines: [String] = []

        lines.append("# RawLogCam 1D Inverse LUT — \(curve.displayName)")
        lines.append("TITLE \"RawLogCam \(curve.displayName) 1D Inverse\"")
        lines.append("LUT_1D_SIZE \(size)")
        lines.append("DOMAIN_MIN 0.0")
        lines.append("DOMAIN_MAX 1.0")
        lines.append("")

        let step = 1.0 / Float(size - 1)
        for i in 0..<size {
            let encoded = Float(i) * step
            let linear = LogCurve.inverse(SIMD3<Float>(repeating: encoded), type: curve)
            let display = applyRec709Gamma(linear)
            let clamped = max(0, min(1, display.x))
            lines.append(String(format: "%.6f %.6f %.6f", clamped, clamped, clamped))
        }

        return lines.joined(separator: "\n")
    }
}
